---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: charmed-osm-com
spec:
  selector:
    app: charmed-osm.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: charmed-osm-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: charmed-osm.com
    spec:
      containers:
        - name: charmed-osm-com
          image: prod-comms.docker-registry.canonical.com/charmed-osm.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
            - configMapRef:
                name: proxy-config
                optional: true
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
