---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: developer-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'developer.ubuntu.com' ) {
        rewrite ^ https://developer.ubuntu.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: developer-ubuntu-com-tls
    hosts:
    - developer.ubuntu.com
  rules:
  - host: developer.ubuntu.com
    http: &developer-ubuntu-com_service
      paths:
      - path: /
        backend:
          serviceName: developer-ubuntu-com
          servicePort: 80

  # Alias domains
  - host: developers.ubuntu.com
    http: *developer-ubuntu-com_service
  - host: dev.ubuntu.com
    http: *developer-ubuntu-com_service

---
