---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: threesixty-staging-canonical-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: threesixty-staging-canonical-com-tls
    hosts:
    - 360.staging.canonical.com
  rules:
  - host: 360.staging.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: threesixty-canonical-com
          servicePort: 80

---
