---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: design-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: design-staging-ubuntu-com-tls
    hosts:
    - design.staging.ubuntu.com
  rules:
  - host: design.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: design-ubuntu-com
          servicePort: 80

---
