---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: old-docs-staging-maas-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host != 'old-docs.staging.maas.io' ) {
        rewrite ^ https://old-docs.staging.maas.io$request_uri? permanent;
      }
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: old-docs-staging-maas-io-tls
    hosts:
    - old-docs.staging.maas.io
  - secretName: docs-staging-maas-io-tls
    hosts:
    - docs.staging.maas.io
  rules:
  - host: old-docs.staging.maas.io
    http: &old-docs-maas-io_service
      paths:
      - path: /
        backend:
          serviceName: old-docs-maas-io
          servicePort: 80

  # Alias domains
  # - host: docs.staging.maas.io
  #   http: *old-docs-maas-io_service

---
