name: canonical-com
domain: canonical.com

# Production
replicas: 20
containerImage: prod-comms.docker-registry.canonical.com/canonical.com
containerTag: latest

useSquid: true
sentryDsn: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14

nginxConfig:  |
  if ($host != 'canonical.com' ) {
    rewrite ^ https://canonical.com$request_uri? permanent;
  }
  more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
